<?php
namespace LoaderImage;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-03-21 at 10:35:05.
 */
class ParseUrlTest extends \PHPUnit_Framework_TestCase 
{

    /**
     * @var ParseUrl
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() 
    {
        $this->object = new ParseUrl;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() 
    {
        
    }


    /**
     * @covers ParseUrl::urlToHost
     * @todo   Implement testUrlToHost().
     * @dataProvider toHostProvider
     */
    public function testUrlToHost($url, $host) 
    {
        $this->assertEquals($host, $this->object->urlToHost($url));
    }

    public function toHostProvider()
    {
        return array(
            array('http://scott.ua/', 'http://scott.ua'),
            array('https://hexa.com.ua/contacts.html', 'https://hexa.com.ua'),
            array('http://fulllink', 'http://fulllink')
        );
    }
    
    /**
     * @covers ParseUrl::isValidUrl
     * @todo   Implement testIsValidUrl().
     * @dataProvider validUrlProvider
     */
    public function testIsValidUrl($url) 
    {
        $this->assertTrue($this->object->isValidUrl($url));
    }

    public function validUrlProvider()
    {
        return array(
            array('http://scott.ua/'),
            array('http://olx.ua/'),
            array('https://hexa.com.ua/contacts.html'),
            array('http://fulllink'),
            array('http://noisset.com.ua/')
        );
    }
    
     /**
     * @covers ParseUrl::validSrc
     * @todo   Implement testValidSrc().
     * @dataProvider validSrcProvider
     */
    public function testValidSrc($url, $src)
    {
        $link = 'https://hexa.com.ua/';
        $this->object->setUrl($link);
        
        $this->assertEquals($src, $this->object->validSrc($url));
    }
    
    public function validSrcProvider() 
    {
        return array(
            array('/assets/img1.jpg', 'https://hexa.com.ua/assets/img1.jpg'),
            array('assets/img1.jpg', 'https://hexa.com.ua/assets/img1.jpg'),
            array('https://hexa.com.ua/assets/img1.jpg', 'https://hexa.com.ua/assets/img1.jpg')
        ); 
    }


}
